"""2024-03-17T00:28:36.215758

Revision ID: 6316e1caa965
Revises: e65304025e68
Create Date: 2024-03-17 00:28:36.461985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6316e1caa965"
down_revision = "e65304025e68"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("auth_user_id_fkey", "auth", type_="foreignkey")
    op.create_foreign_key(
        None,
        "auth",
        "user",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.add_column("user", sa.Column("nickname", sa.String(length=50), nullable=False))
    op.alter_column(
        "user",
        "description",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=150),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "image_url",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=300),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "user", ["nickname"], schema="public")
    op.drop_column("user", "name")
    op.drop_column("user", "surname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("surname", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "user", schema="public", type_="unique")
    op.alter_column(
        "user",
        "image_url",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "description",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_column("user", "nickname")
    op.drop_constraint(None, "auth", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "auth_user_id_fkey", "auth", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
