name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOMAIN: ${{ env.DOMAIN }}
      SMTP_CADDY_USER: ${{ env.SMTP_CADDY_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose build
          docker-compose up

      - name: Stop Docker Compose
        run: docker-compose down
