name: Mypy Check

on: [push, pull_request]

jobs:
  mypy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install mypy types-redis

      - name: Run MyPy
        run: |
          mypy --config-file mypy.ini .
